/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.BenhNhan ;

/**
 * Very basic cache for BenhNhan instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class BenhNhanCache
{
	private final static Map<String,BenhNhan> cache = new Hashtable<String,BenhNhan>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param bnId BN_ID 
	 * @return the key
	 */
	private final static String getKey( Integer bnId ) {
		return ""  + bnId  ;
	}

	/**
	 * Put the given BenhNhan instance in the cache
	 * @param BenhNhan instance to be stored
	 */
	public final static void putBenhNhan(BenhNhan benhNhan ) {
		String key = getKey( benhNhan.getBN_ID());
		cache.put(key, benhNhan );
	}
	
	/**
	 * Get the BenhNhan instance for the given primary key
     * @param bnId 
	 * @return the BenhNhan instance (or null if none)
	 */
	public final static BenhNhan getBenhNhan( Integer bnId ) {
		String key = getKey( bnId ) ;
		return cache.get(key);
	}

	/**
	 * Removes the BenhNhan associated with the given primary key
     * @param bnId 
	 */
	public final static void removeBenhNhan ( Integer bnId ) {
		String key = getKey( bnId ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given BenhNhan from the cache using its primary key
	 * @param BenhNhan instance to be removed
	 */
	public final static void removeBenhNhan (BenhNhan benhNhan ) { 
		String key = getKey( benhNhan.getBN_ID());
		cache.remove(key);
	}

}
