/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.Chisoxn ;

/**
 * Very basic cache for Chisoxn instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class ChisoxnCache
{
	private final static Map<String,Chisoxn> cache = new Hashtable<String,Chisoxn>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param csvnId CSVN_ID 
	 * @return the key
	 */
	private final static String getKey( Integer csvnId ) {
		return ""  + csvnId  ;
	}

	/**
	 * Put the given Chisoxn instance in the cache
	 * @param Chisoxn instance to be stored
	 */
	public final static void putChisoxn(Chisoxn chisoxn ) {
		String key = getKey( chisoxn.getCSVN_ID());
		cache.put(key, chisoxn );
	}
	
	/**
	 * Get the Chisoxn instance for the given primary key
     * @param csvnId 
	 * @return the Chisoxn instance (or null if none)
	 */
	public final static Chisoxn getChisoxn( Integer csvnId ) {
		String key = getKey( csvnId ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Chisoxn associated with the given primary key
     * @param csvnId 
	 */
	public final static void removeChisoxn ( Integer csvnId ) {
		String key = getKey( csvnId ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Chisoxn from the cache using its primary key
	 * @param Chisoxn instance to be removed
	 */
	public final static void removeChisoxn (Chisoxn chisoxn ) { 
		String key = getKey( chisoxn.getCSVN_ID());
		cache.remove(key);
	}

}
