/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.Dichvu ;

/**
 * Very basic cache for Dichvu instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class DichvuCache
{
	private final static Map<String,Dichvu> cache = new Hashtable<String,Dichvu>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param dvId DV_ID 
	 * @return the key
	 */
	private final static String getKey( Integer dvId ) {
		return ""  + dvId  ;
	}

	/**
	 * Put the given Dichvu instance in the cache
	 * @param Dichvu instance to be stored
	 */
	public final static void putDichvu(Dichvu dichvu ) {
		String key = getKey( dichvu.getDV_ID());
		cache.put(key, dichvu );
	}
	
	/**
	 * Get the Dichvu instance for the given primary key
     * @param dvId 
	 * @return the Dichvu instance (or null if none)
	 */
	public final static Dichvu getDichvu( Integer dvId ) {
		String key = getKey( dvId ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Dichvu associated with the given primary key
     * @param dvId 
	 */
	public final static void removeDichvu ( Integer dvId ) {
		String key = getKey( dvId ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Dichvu from the cache using its primary key
	 * @param Dichvu instance to be removed
	 */
	public final static void removeDichvu (Dichvu dichvu ) { 
		String key = getKey( dichvu.getDV_ID());
		cache.remove(key);
	}

}
