/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.DonviTinh ;

/**
 * Very basic cache for DonviTinh instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class DonviTinhCache
{
	private final static Map<String,DonviTinh> cache = new Hashtable<String,DonviTinh>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param dvtMa DVT_MA 
	 * @return the key
	 */
	private final static String getKey( Integer dvtMa ) {
		return ""  + dvtMa  ;
	}

	/**
	 * Put the given DonviTinh instance in the cache
	 * @param DonviTinh instance to be stored
	 */
	public final static void putDonviTinh(DonviTinh donviTinh ) {
		String key = getKey( donviTinh.getDVT_MA());
		cache.put(key, donviTinh );
	}
	
	/**
	 * Get the DonviTinh instance for the given primary key
     * @param dvtMa 
	 * @return the DonviTinh instance (or null if none)
	 */
	public final static DonviTinh getDonviTinh( Integer dvtMa ) {
		String key = getKey( dvtMa ) ;
		return cache.get(key);
	}

	/**
	 * Removes the DonviTinh associated with the given primary key
     * @param dvtMa 
	 */
	public final static void removeDonviTinh ( Integer dvtMa ) {
		String key = getKey( dvtMa ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given DonviTinh from the cache using its primary key
	 * @param DonviTinh instance to be removed
	 */
	public final static void removeDonviTinh (DonviTinh donviTinh ) { 
		String key = getKey( donviTinh.getDVT_MA());
		cache.remove(key);
	}

}
