/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.KetquaXn ;

/**
 * Very basic cache for KetquaXn instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class KetquaXnCache
{
	private final static Map<String,KetquaXn> cache = new Hashtable<String,KetquaXn>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param kqxnId KQXN_ID 
	 * @return the key
	 */
	private final static String getKey( Integer kqxnId ) {
		return ""  + kqxnId  ;
	}

	/**
	 * Put the given KetquaXn instance in the cache
	 * @param KetquaXn instance to be stored
	 */
	public final static void putKetquaXn(KetquaXn ketquaXn ) {
		String key = getKey( ketquaXn.getKQXN_ID());
		cache.put(key, ketquaXn );
	}
	
	/**
	 * Get the KetquaXn instance for the given primary key
     * @param kqxnId 
	 * @return the KetquaXn instance (or null if none)
	 */
	public final static KetquaXn getKetquaXn( Integer kqxnId ) {
		String key = getKey( kqxnId ) ;
		return cache.get(key);
	}

	/**
	 * Removes the KetquaXn associated with the given primary key
     * @param kqxnId 
	 */
	public final static void removeKetquaXn ( Integer kqxnId ) {
		String key = getKey( kqxnId ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given KetquaXn from the cache using its primary key
	 * @param KetquaXn instance to be removed
	 */
	public final static void removeKetquaXn (KetquaXn ketquaXn ) { 
		String key = getKey( ketquaXn.getKQXN_ID());
		cache.remove(key);
	}

}
