/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.KhamBenh ;

/**
 * Very basic cache for KhamBenh instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class KhamBenhCache
{
	private final static Map<String,KhamBenh> cache = new Hashtable<String,KhamBenh>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param maLk MA_LK 
	 * @return the key
	 */
	private final static String getKey( Integer maLk ) {
		return ""  + maLk  ;
	}

	/**
	 * Put the given KhamBenh instance in the cache
	 * @param KhamBenh instance to be stored
	 */
	public final static void putKhamBenh(KhamBenh khamBenh ) {
		String key = getKey( khamBenh.getMA_LK());
		cache.put(key, khamBenh );
	}
	
	/**
	 * Get the KhamBenh instance for the given primary key
     * @param maLk 
	 * @return the KhamBenh instance (or null if none)
	 */
	public final static KhamBenh getKhamBenh( Integer maLk ) {
		String key = getKey( maLk ) ;
		return cache.get(key);
	}

	/**
	 * Removes the KhamBenh associated with the given primary key
     * @param maLk 
	 */
	public final static void removeKhamBenh ( Integer maLk ) {
		String key = getKey( maLk ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given KhamBenh from the cache using its primary key
	 * @param KhamBenh instance to be removed
	 */
	public final static void removeKhamBenh (KhamBenh khamBenh ) { 
		String key = getKey( khamBenh.getMA_LK());
		cache.remove(key);
	}

}
