/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.Khohang ;

/**
 * Very basic cache for Khohang instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class KhohangCache
{
	private final static Map<String,Khohang> cache = new Hashtable<String,Khohang>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param khoId KHO_ID 
	 * @return the key
	 */
	private final static String getKey( Integer khoId ) {
		return ""  + khoId  ;
	}

	/**
	 * Put the given Khohang instance in the cache
	 * @param Khohang instance to be stored
	 */
	public final static void putKhohang(Khohang khohang ) {
		String key = getKey( khohang.getKHO_ID());
		cache.put(key, khohang );
	}
	
	/**
	 * Get the Khohang instance for the given primary key
     * @param khoId 
	 * @return the Khohang instance (or null if none)
	 */
	public final static Khohang getKhohang( Integer khoId ) {
		String key = getKey( khoId ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Khohang associated with the given primary key
     * @param khoId 
	 */
	public final static void removeKhohang ( Integer khoId ) {
		String key = getKey( khoId ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Khohang from the cache using its primary key
	 * @param Khohang instance to be removed
	 */
	public final static void removeKhohang (Khohang khohang ) { 
		String key = getKey( khohang.getKHO_ID());
		cache.remove(key);
	}

}
