/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.MaCskcb ;

/**
 * Very basic cache for MaCskcb instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class MaCskcbCache
{
	private final static Map<String,MaCskcb> cache = new Hashtable<String,MaCskcb>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param maCode MA_CODE 
	 * @return the key
	 */
	private final static String getKey( String maCode ) {
		return ""  + maCode  ;
	}

	/**
	 * Put the given MaCskcb instance in the cache
	 * @param MaCskcb instance to be stored
	 */
	public final static void putMaCskcb(MaCskcb maCskcb ) {
		String key = getKey( maCskcb.getMA_CODE());
		cache.put(key, maCskcb );
	}
	
	/**
	 * Get the MaCskcb instance for the given primary key
     * @param maCode 
	 * @return the MaCskcb instance (or null if none)
	 */
	public final static MaCskcb getMaCskcb( String maCode ) {
		String key = getKey( maCode ) ;
		return cache.get(key);
	}

	/**
	 * Removes the MaCskcb associated with the given primary key
     * @param maCode 
	 */
	public final static void removeMaCskcb ( String maCode ) {
		String key = getKey( maCode ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given MaCskcb from the cache using its primary key
	 * @param MaCskcb instance to be removed
	 */
	public final static void removeMaCskcb (MaCskcb maCskcb ) { 
		String key = getKey( maCskcb.getMA_CODE());
		cache.remove(key);
	}

}
