/*
 * Very basic JavaBean cache
 * Created on 17 Jul 2017 ( Date ISO 2017-07-17 - Time 08:25:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.model.cache;

import java.util.Hashtable;
import java.util.ArrayList;
import java.util.Map;

import com.model.dao.MstChiso ;

/**
 * Very basic cache for MstChiso instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class MstChisoCache
{
	private final static Map<String,MstChiso> cache = new Hashtable<String,MstChiso>() ;
	public final static ArrayList<String> cacheArrayListKey = new ArrayList<String>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param csId CS_ID 
	 * @return the key
	 */
	private final static String getKey( Integer csId ) {
		return ""  + csId  ;
	}

	/**
	 * Put the given MstChiso instance in the cache
	 * @param MstChiso instance to be stored
	 */
	public final static void putMstChiso(MstChiso mstChiso ) {
		String key = getKey( mstChiso.getCS_ID());
		cache.put(key, mstChiso );
	}
	
	/**
	 * Get the MstChiso instance for the given primary key
     * @param csId 
	 * @return the MstChiso instance (or null if none)
	 */
	public final static MstChiso getMstChiso( Integer csId ) {
		String key = getKey( csId ) ;
		return cache.get(key);
	}

	/**
	 * Removes the MstChiso associated with the given primary key
     * @param csId 
	 */
	public final static void removeMstChiso ( Integer csId ) {
		String key = getKey( csId ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given MstChiso from the cache using its primary key
	 * @param MstChiso instance to be removed
	 */
	public final static void removeMstChiso (MstChiso mstChiso ) { 
		String key = getKey( mstChiso.getCS_ID());
		cache.remove(key);
	}

}
