/*
 * Java bean class for entity table dv_chitiet 
 * Created on 15 Dec 2017 ( Date ISO 2017-12-15 - Time 14:28:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 * template update by NEO
 */

package com.model.dao;

import java.io.Serializable;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.sql2o.Connection;
import com.DbHelper;

import java.util.Date;
import java.util.List;

import java.util.Date;

/**
 * Entity bean for table "dv_chitiet"
 * 
 * @author Telosys Tools Generator
 *
 */
public class DvChitiet implements Serializable
{
    static Logger logger = LogManager.getLogger(DvChitiet.class.getName());
    private static final long serialVersionUID = 1L;

    public Integer    DVCT_ID ; // Primary Key

    public Integer    BN_ID ;
    public Integer    MA_LK ;
    public Integer    DV_ID ;
    public String     MA_DICH_VU ;
    public String     MA_VAT_TU ;
    public Integer    MA_NHOM ;
    public String     GOI_VTYT ;
    public String     TEN_VAT_TU ;
    public String     TEN_DICH_VU ;
    public String     DON_VI_TINH ;
    public Integer    PHAM_VI ;
    public Integer    SO_LUONG ;
    public Integer    DON_GIA ;
    public Integer    DON_GIA2 ;
    public String     TT_THAU ;
    public Integer    THANH_TIEN ;
    public Integer    THANH_TIEN2 ;
    public Integer    T_TRANTT ;
    public Integer    TYLE_TT ;
    public Integer    T_NGUONKHAC ;
    public Integer    TT_BHTT ;
    public Integer    TT_BNTT ;
    public Integer    T_BNCCT ;
    public Integer    T_NGOAIDS ;
    public String     MA_GIUONG ;
    public String     MA_KHOA ;
    public String     MA_BAC_SI ;
    public String     MA_BENH ;
    public String     NGAY_YL ;
    public String     NGAY_KQ ;
    public Integer    MA_PTTT ;
    public Integer    MUC_HUONG ;
    public Date       CUR_DATE ;
    public Integer    TYP ;
    public Integer    THANHTOAN ;
    public Integer    NV_ID ;
    public String     NV_NAME ;
    public Integer    NHOM_DV ;
    public Integer    STS ;

    /**
     * Default constructor
     */
    public DvChitiet()
    {
        super();
        // Set default value 
this.BN_ID = 0;                         // data type = Integer   
this.MA_LK = 0;                         // data type = Integer   
this.DV_ID = 0;                         // data type = Integer   
this.MA_DICH_VU = "";//String.format("%50.50s", "MA_DICH_VU").trim(); // data type = String     50
this.MA_VAT_TU = "";//String.format("%255.255s", "MA_VAT_TU").trim(); // data type = String     255
this.MA_NHOM = 0;                         // data type = Integer   
this.GOI_VTYT = "";//String.format("%2.2s", "GOI_VTYT").trim(); // data type = String     2
this.TEN_VAT_TU = "";//String.format("%16.16s", "TEN_VAT_TU").trim(); // data type = String     16
this.TEN_DICH_VU = "";//String.format("%2000.2000s", "TEN_DICH_VU").trim(); // data type = String     2000
this.DON_VI_TINH = "";//String.format("%16.16s", "DON_VI_TINH").trim(); // data type = String     16
this.PHAM_VI = 0;                         // data type = Integer   
this.SO_LUONG = 0;                         // data type = Integer   
this.DON_GIA = 0;                         // data type = Integer   
this.DON_GIA2 = 0;                         // data type = Integer   
this.TT_THAU = "";//String.format("%50.50s", "TT_THAU").trim(); // data type = String     50
this.THANH_TIEN = 0;                         // data type = Integer   
this.THANH_TIEN2 = 0;                         // data type = Integer   
this.T_TRANTT = 0;                         // data type = Integer   
this.TYLE_TT = 0;                         // data type = Integer   
this.T_NGUONKHAC = 0;                         // data type = Integer   
this.TT_BHTT = 0;                         // data type = Integer   
this.TT_BNTT = 0;                         // data type = Integer   
this.T_BNCCT = 0;                         // data type = Integer   
this.T_NGOAIDS = 0;                         // data type = Integer   
this.MA_GIUONG = "";//String.format("%16.16s", "MA_GIUONG").trim(); // data type = String     16
this.MA_KHOA = "";//String.format("%3.3s", "MA_KHOA").trim(); // data type = String     3
this.MA_BAC_SI = "";//String.format("%16.16s", "MA_BAC_SI").trim(); // data type = String     16
this.MA_BENH = "";//String.format("%255.255s", "MA_BENH").trim(); // data type = String     255
this.NGAY_YL = "";//String.format("%12.12s", "NGAY_YL").trim(); // data type = String     12
this.NGAY_KQ = "";//String.format("%12.12s", "NGAY_KQ").trim(); // data type = String     12
this.MA_PTTT = 0;                         // data type = Integer   
this.MUC_HUONG = 0;                         // data type = Integer   
this.CUR_DATE = new java.util.Date();      // data type = Date      
this.TYP = 0;                         // data type = Integer   
this.THANHTOAN = 0;                         // data type = Integer   
this.NV_ID = 0;                         // data type = Integer   
this.NV_NAME = "";//String.format("%16.16s", "NV_NAME").trim(); // data type = String     16
this.NHOM_DV = 0;                         // data type = Integer   
this.STS = 0;                         // data type = Integer   
        // End Set default value 
    }
    
    public void copy(DvChitiet fromObj)
    {
        if(fromObj==null){
            return;
        }
        this.BN_ID = fromObj.BN_ID;
        this.MA_LK = fromObj.MA_LK;
        this.DV_ID = fromObj.DV_ID;
        this.MA_DICH_VU = fromObj.MA_DICH_VU;
        this.MA_VAT_TU = fromObj.MA_VAT_TU;
        this.MA_NHOM = fromObj.MA_NHOM;
        this.GOI_VTYT = fromObj.GOI_VTYT;
        this.TEN_VAT_TU = fromObj.TEN_VAT_TU;
        this.TEN_DICH_VU = fromObj.TEN_DICH_VU;
        this.DON_VI_TINH = fromObj.DON_VI_TINH;
        this.PHAM_VI = fromObj.PHAM_VI;
        this.SO_LUONG = fromObj.SO_LUONG;
        this.DON_GIA = fromObj.DON_GIA;
        this.DON_GIA2 = fromObj.DON_GIA2;
        this.TT_THAU = fromObj.TT_THAU;
        this.THANH_TIEN = fromObj.THANH_TIEN;
        this.THANH_TIEN2 = fromObj.THANH_TIEN2;
        this.T_TRANTT = fromObj.T_TRANTT;
        this.TYLE_TT = fromObj.TYLE_TT;
        this.T_NGUONKHAC = fromObj.T_NGUONKHAC;
        this.TT_BHTT = fromObj.TT_BHTT;
        this.TT_BNTT = fromObj.TT_BNTT;
        this.T_BNCCT = fromObj.T_BNCCT;
        this.T_NGOAIDS = fromObj.T_NGOAIDS;
        this.MA_GIUONG = fromObj.MA_GIUONG;
        this.MA_KHOA = fromObj.MA_KHOA;
        this.MA_BAC_SI = fromObj.MA_BAC_SI;
        this.MA_BENH = fromObj.MA_BENH;
        this.NGAY_YL = fromObj.NGAY_YL;
        this.NGAY_KQ = fromObj.NGAY_KQ;
        this.MA_PTTT = fromObj.MA_PTTT;
        this.MUC_HUONG = fromObj.MUC_HUONG;
        this.CUR_DATE = fromObj.CUR_DATE;
        this.TYP = fromObj.TYP;
        this.THANHTOAN = fromObj.THANHTOAN;
        this.NV_ID = fromObj.NV_ID;
        this.NV_NAME = fromObj.NV_NAME;
        this.NHOM_DV = fromObj.NHOM_DV;
        this.STS = fromObj.STS;
    }
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "dvctId" field value
     * This field is mapped on the database column "DVCT_ID" ( type "INT", NotNull : true ) 
     * @param DVCT_ID
     */
	public void setDVCT_ID( Integer DVCT_ID )
    {
        this.DVCT_ID = DVCT_ID ;
    }
    /**
     * Get the "DVCT_ID" field value
     * This field is mapped on the database column "DVCT_ID" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getDVCT_ID()
    {
        return this.DVCT_ID;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : BN_ID ( INT ) 
    /**
     * Set the "BN_ID" field value
     * This field is mapped on the database column "BN_ID" ( type "INT", NotNull : true ) 
     * @param BN_ID
     */
    public void setBN_ID( Integer BN_ID )
    {
        this.BN_ID = BN_ID;
    }
    /**
     * Get the "bnId" field value
     * This field is mapped on the database column "BN_ID" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getBN_ID()
    {
        return this.BN_ID;
    }

    //--- DATABASE MAPPING : MA_LK ( INT ) 
    /**
     * Set the "MA_LK" field value
     * This field is mapped on the database column "MA_LK" ( type "INT", NotNull : true ) 
     * @param MA_LK
     */
    public void setMA_LK( Integer MA_LK )
    {
        this.MA_LK = MA_LK;
    }
    /**
     * Get the "maLk" field value
     * This field is mapped on the database column "MA_LK" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getMA_LK()
    {
        return this.MA_LK;
    }

    //--- DATABASE MAPPING : DV_ID ( INT ) 
    /**
     * Set the "DV_ID" field value
     * This field is mapped on the database column "DV_ID" ( type "INT", NotNull : true ) 
     * @param DV_ID
     */
    public void setDV_ID( Integer DV_ID )
    {
        this.DV_ID = DV_ID;
    }
    /**
     * Get the "dvId" field value
     * This field is mapped on the database column "DV_ID" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getDV_ID()
    {
        return this.DV_ID;
    }

    //--- DATABASE MAPPING : MA_DICH_VU ( VARCHAR ) 
    /**
     * Set the "MA_DICH_VU" field value
     * This field is mapped on the database column "MA_DICH_VU" ( type "VARCHAR", NotNull : true ) 
     * @param MA_DICH_VU
     */
    public void setMA_DICH_VU( String MA_DICH_VU )
    {
        this.MA_DICH_VU = MA_DICH_VU;
    }
    /**
     * Get the "maDichVu" field value
     * This field is mapped on the database column "MA_DICH_VU" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getMA_DICH_VU()
    {
        return this.MA_DICH_VU;
    }

    //--- DATABASE MAPPING : MA_VAT_TU ( VARCHAR ) 
    /**
     * Set the "MA_VAT_TU" field value
     * This field is mapped on the database column "MA_VAT_TU" ( type "VARCHAR", NotNull : true ) 
     * @param MA_VAT_TU
     */
    public void setMA_VAT_TU( String MA_VAT_TU )
    {
        this.MA_VAT_TU = MA_VAT_TU;
    }
    /**
     * Get the "maVatTu" field value
     * This field is mapped on the database column "MA_VAT_TU" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getMA_VAT_TU()
    {
        return this.MA_VAT_TU;
    }

    //--- DATABASE MAPPING : MA_NHOM ( INT ) 
    /**
     * Set the "MA_NHOM" field value
     * This field is mapped on the database column "MA_NHOM" ( type "INT", NotNull : true ) 
     * @param MA_NHOM
     */
    public void setMA_NHOM( Integer MA_NHOM )
    {
        this.MA_NHOM = MA_NHOM;
    }
    /**
     * Get the "maNhom" field value
     * This field is mapped on the database column "MA_NHOM" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getMA_NHOM()
    {
        return this.MA_NHOM;
    }

    //--- DATABASE MAPPING : GOI_VTYT ( VARCHAR ) 
    /**
     * Set the "GOI_VTYT" field value
     * This field is mapped on the database column "GOI_VTYT" ( type "VARCHAR", NotNull : false ) 
     * @param GOI_VTYT
     */
    public void setGOI_VTYT( String GOI_VTYT )
    {
        this.GOI_VTYT = GOI_VTYT;
    }
    /**
     * Get the "goiVtyt" field value
     * This field is mapped on the database column "GOI_VTYT" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getGOI_VTYT()
    {
        return this.GOI_VTYT;
    }

    //--- DATABASE MAPPING : TEN_VAT_TU ( VARCHAR ) 
    /**
     * Set the "TEN_VAT_TU" field value
     * This field is mapped on the database column "TEN_VAT_TU" ( type "VARCHAR", NotNull : false ) 
     * @param TEN_VAT_TU
     */
    public void setTEN_VAT_TU( String TEN_VAT_TU )
    {
        this.TEN_VAT_TU = TEN_VAT_TU;
    }
    /**
     * Get the "tenVatTu" field value
     * This field is mapped on the database column "TEN_VAT_TU" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getTEN_VAT_TU()
    {
        return this.TEN_VAT_TU;
    }

    //--- DATABASE MAPPING : TEN_DICH_VU ( VARCHAR ) 
    /**
     * Set the "TEN_DICH_VU" field value
     * This field is mapped on the database column "TEN_DICH_VU" ( type "VARCHAR", NotNull : true ) 
     * @param TEN_DICH_VU
     */
    public void setTEN_DICH_VU( String TEN_DICH_VU )
    {
        this.TEN_DICH_VU = TEN_DICH_VU;
    }
    /**
     * Get the "tenDichVu" field value
     * This field is mapped on the database column "TEN_DICH_VU" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getTEN_DICH_VU()
    {
        return this.TEN_DICH_VU;
    }

    //--- DATABASE MAPPING : DON_VI_TINH ( VARCHAR ) 
    /**
     * Set the "DON_VI_TINH" field value
     * This field is mapped on the database column "DON_VI_TINH" ( type "VARCHAR", NotNull : true ) 
     * @param DON_VI_TINH
     */
    public void setDON_VI_TINH( String DON_VI_TINH )
    {
        this.DON_VI_TINH = DON_VI_TINH;
    }
    /**
     * Get the "donViTinh" field value
     * This field is mapped on the database column "DON_VI_TINH" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getDON_VI_TINH()
    {
        return this.DON_VI_TINH;
    }

    //--- DATABASE MAPPING : PHAM_VI ( INT ) 
    /**
     * Set the "PHAM_VI" field value
     * This field is mapped on the database column "PHAM_VI" ( type "INT", NotNull : true ) 
     * @param PHAM_VI
     */
    public void setPHAM_VI( Integer PHAM_VI )
    {
        this.PHAM_VI = PHAM_VI;
    }
    /**
     * Get the "phamVi" field value
     * This field is mapped on the database column "PHAM_VI" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getPHAM_VI()
    {
        return this.PHAM_VI;
    }

    //--- DATABASE MAPPING : SO_LUONG ( INT ) 
    /**
     * Set the "SO_LUONG" field value
     * This field is mapped on the database column "SO_LUONG" ( type "INT", NotNull : true ) 
     * @param SO_LUONG
     */
    public void setSO_LUONG( Integer SO_LUONG )
    {
        this.SO_LUONG = SO_LUONG;
    }
    /**
     * Get the "soLuong" field value
     * This field is mapped on the database column "SO_LUONG" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getSO_LUONG()
    {
        return this.SO_LUONG;
    }

    //--- DATABASE MAPPING : DON_GIA ( INT ) 
    /**
     * Set the "DON_GIA" field value
     * This field is mapped on the database column "DON_GIA" ( type "INT", NotNull : true ) 
     * @param DON_GIA
     */
    public void setDON_GIA( Integer DON_GIA )
    {
        this.DON_GIA = DON_GIA;
    }
    /**
     * Get the "donGia" field value
     * This field is mapped on the database column "DON_GIA" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getDON_GIA()
    {
        return this.DON_GIA;
    }

    //--- DATABASE MAPPING : DON_GIA2 ( INT ) 
    /**
     * Set the "DON_GIA2" field value
     * This field is mapped on the database column "DON_GIA2" ( type "INT", NotNull : false ) 
     * @param DON_GIA2
     */
    public void setDON_GIA2( Integer DON_GIA2 )
    {
        this.DON_GIA2 = DON_GIA2;
    }
    /**
     * Get the "donGia2" field value
     * This field is mapped on the database column "DON_GIA2" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getDON_GIA2()
    {
        return this.DON_GIA2;
    }

    //--- DATABASE MAPPING : TT_THAU ( VARCHAR ) 
    /**
     * Set the "TT_THAU" field value
     * This field is mapped on the database column "TT_THAU" ( type "VARCHAR", NotNull : false ) 
     * @param TT_THAU
     */
    public void setTT_THAU( String TT_THAU )
    {
        this.TT_THAU = TT_THAU;
    }
    /**
     * Get the "ttThau" field value
     * This field is mapped on the database column "TT_THAU" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getTT_THAU()
    {
        return this.TT_THAU;
    }

    //--- DATABASE MAPPING : THANH_TIEN ( INT ) 
    /**
     * Set the "THANH_TIEN" field value
     * This field is mapped on the database column "THANH_TIEN" ( type "INT", NotNull : true ) 
     * @param THANH_TIEN
     */
    public void setTHANH_TIEN( Integer THANH_TIEN )
    {
        this.THANH_TIEN = THANH_TIEN;
    }
    /**
     * Get the "thanhTien" field value
     * This field is mapped on the database column "THANH_TIEN" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getTHANH_TIEN()
    {
        return this.THANH_TIEN;
    }

    //--- DATABASE MAPPING : THANH_TIEN2 ( INT ) 
    /**
     * Set the "THANH_TIEN2" field value
     * This field is mapped on the database column "THANH_TIEN2" ( type "INT", NotNull : true ) 
     * @param THANH_TIEN2
     */
    public void setTHANH_TIEN2( Integer THANH_TIEN2 )
    {
        this.THANH_TIEN2 = THANH_TIEN2;
    }
    /**
     * Get the "thanhTien2" field value
     * This field is mapped on the database column "THANH_TIEN2" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getTHANH_TIEN2()
    {
        return this.THANH_TIEN2;
    }

    //--- DATABASE MAPPING : T_TRANTT ( INT ) 
    /**
     * Set the "T_TRANTT" field value
     * This field is mapped on the database column "T_TRANTT" ( type "INT", NotNull : true ) 
     * @param T_TRANTT
     */
    public void setT_TRANTT( Integer T_TRANTT )
    {
        this.T_TRANTT = T_TRANTT;
    }
    /**
     * Get the "tTrantt" field value
     * This field is mapped on the database column "T_TRANTT" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getT_TRANTT()
    {
        return this.T_TRANTT;
    }

    //--- DATABASE MAPPING : MUC_HUONG ( INT ) 
    /**
     * Set the "MUC_HUONG" field value
     * This field is mapped on the database column "MUC_HUONG" ( type "INT", NotNull : true ) 
     * @param MUC_HUONG
     */
    public void setMUC_HUONG( Integer MUC_HUONG )
    {
        this.TYLE_TT = MUC_HUONG;
    }
    /**
     * Get the "mucHuong" field value
     * This field is mapped on the database column "MUC_HUONG" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getMUC_HUONG()
    {
        return this.TYLE_TT;
    }

    //--- DATABASE MAPPING : T_NGUONKHAC ( INT ) 
    /**
     * Set the "T_NGUONKHAC" field value
     * This field is mapped on the database column "T_NGUONKHAC" ( type "INT", NotNull : true ) 
     * @param T_NGUONKHAC
     */
    public void setT_NGUONKHAC( Integer T_NGUONKHAC )
    {
        this.T_NGUONKHAC = T_NGUONKHAC;
    }
    /**
     * Get the "tNguonkhac" field value
     * This field is mapped on the database column "T_NGUONKHAC" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getT_NGUONKHAC()
    {
        return this.T_NGUONKHAC;
    }

    //--- DATABASE MAPPING : TT_BHTT ( INT ) 
    /**
     * Set the "TT_BHTT" field value
     * This field is mapped on the database column "TT_BHTT" ( type "INT", NotNull : true ) 
     * @param TT_BHTT
     */
    public void setTT_BHTT( Integer TT_BHTT )
    {
        this.TT_BHTT = TT_BHTT;
    }
    /**
     * Get the "ttBhtt" field value
     * This field is mapped on the database column "TT_BHTT" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getTT_BHTT()
    {
        return this.TT_BHTT;
    }

    //--- DATABASE MAPPING : TT_BNTT ( INT ) 
    /**
     * Set the "TT_BNTT" field value
     * This field is mapped on the database column "TT_BNTT" ( type "INT", NotNull : true ) 
     * @param TT_BNTT
     */
    public void setTT_BNTT( Integer TT_BNTT )
    {
        this.TT_BNTT = TT_BNTT;
    }
    /**
     * Get the "ttBntt" field value
     * This field is mapped on the database column "TT_BNTT" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getTT_BNTT()
    {
        return this.TT_BNTT;
    }

    //--- DATABASE MAPPING : T_BNCCT ( INT ) 
    /**
     * Set the "T_BNCCT" field value
     * This field is mapped on the database column "T_BNCCT" ( type "INT", NotNull : true ) 
     * @param T_BNCCT
     */
    public void setT_BNCCT( Integer T_BNCCT )
    {
        this.T_BNCCT = T_BNCCT;
    }
    /**
     * Get the "tBncct" field value
     * This field is mapped on the database column "T_BNCCT" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getT_BNCCT()
    {
        return this.T_BNCCT;
    }

    //--- DATABASE MAPPING : T_NGOAIDS ( INT ) 
    /**
     * Set the "T_NGOAIDS" field value
     * This field is mapped on the database column "T_NGOAIDS" ( type "INT", NotNull : true ) 
     * @param T_NGOAIDS
     */
    public void setT_NGOAIDS( Integer T_NGOAIDS )
    {
        this.T_NGOAIDS = T_NGOAIDS;
    }
    /**
     * Get the "tNgoaids" field value
     * This field is mapped on the database column "T_NGOAIDS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getT_NGOAIDS()
    {
        return this.T_NGOAIDS;
    }

    //--- DATABASE MAPPING : MA_GIUONG ( VARCHAR ) 
    /**
     * Set the "MA_GIUONG" field value
     * This field is mapped on the database column "MA_GIUONG" ( type "VARCHAR", NotNull : true ) 
     * @param MA_GIUONG
     */
    public void setMA_GIUONG( String MA_GIUONG )
    {
        this.MA_GIUONG = MA_GIUONG;
    }
    /**
     * Get the "maGiuong" field value
     * This field is mapped on the database column "MA_GIUONG" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getMA_GIUONG()
    {
        return this.MA_GIUONG;
    }

    //--- DATABASE MAPPING : MA_KHOA ( VARCHAR ) 
    /**
     * Set the "MA_KHOA" field value
     * This field is mapped on the database column "MA_KHOA" ( type "VARCHAR", NotNull : true ) 
     * @param MA_KHOA
     */
    public void setMA_KHOA( String MA_KHOA )
    {
        this.MA_KHOA = MA_KHOA;
    }
    /**
     * Get the "maKhoa" field value
     * This field is mapped on the database column "MA_KHOA" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getMA_KHOA()
    {
        return this.MA_KHOA;
    }

    //--- DATABASE MAPPING : MA_BAC_SI ( VARCHAR ) 
    /**
     * Set the "MA_BAC_SI" field value
     * This field is mapped on the database column "MA_BAC_SI" ( type "VARCHAR", NotNull : true ) 
     * @param MA_BAC_SI
     */
    public void setMA_BAC_SI( String MA_BAC_SI )
    {
        this.MA_BAC_SI = MA_BAC_SI;
    }
    /**
     * Get the "maBacSi" field value
     * This field is mapped on the database column "MA_BAC_SI" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getMA_BAC_SI()
    {
        return this.MA_BAC_SI;
    }

    //--- DATABASE MAPPING : MA_BENH ( VARCHAR ) 
    /**
     * Set the "MA_BENH" field value
     * This field is mapped on the database column "MA_BENH" ( type "VARCHAR", NotNull : true ) 
     * @param MA_BENH
     */
    public void setMA_BENH( String MA_BENH )
    {
        this.MA_BENH = MA_BENH;
    }
    /**
     * Get the "maBenh" field value
     * This field is mapped on the database column "MA_BENH" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getMA_BENH()
    {
        return this.MA_BENH;
    }

    //--- DATABASE MAPPING : NGAY_YL ( VARCHAR ) 
    /**
     * Set the "NGAY_YL" field value
     * This field is mapped on the database column "NGAY_YL" ( type "VARCHAR", NotNull : true ) 
     * @param NGAY_YL
     */
    public void setNGAY_YL( String NGAY_YL )
    {
        this.NGAY_YL = NGAY_YL;
    }
    /**
     * Get the "ngayYl" field value
     * This field is mapped on the database column "NGAY_YL" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getNGAY_YL()
    {
        return this.NGAY_YL;
    }

    //--- DATABASE MAPPING : NGAY_KQ ( VARCHAR ) 
    /**
     * Set the "NGAY_KQ" field value
     * This field is mapped on the database column "NGAY_KQ" ( type "VARCHAR", NotNull : true ) 
     * @param NGAY_KQ
     */
    public void setNGAY_KQ( String NGAY_KQ )
    {
        this.NGAY_KQ = NGAY_KQ;
    }
    /**
     * Get the "ngayKq" field value
     * This field is mapped on the database column "NGAY_KQ" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getNGAY_KQ()
    {
        return this.NGAY_KQ;
    }

    //--- DATABASE MAPPING : MA_PTTT ( INT ) 
    /**
     * Set the "MA_PTTT" field value
     * This field is mapped on the database column "MA_PTTT" ( type "INT", NotNull : true ) 
     * @param MA_PTTT
     */
    public void setMA_PTTT( Integer MA_PTTT )
    {
        this.MA_PTTT = MA_PTTT;
    }
    /**
     * Get the "maPttt" field value
     * This field is mapped on the database column "MA_PTTT" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getMA_PTTT()
    {
        return this.MA_PTTT;
    }

    //--- DATABASE MAPPING : TYLE_TT ( INT ) 
    /**
     * Set the "TYLE_TT" field value
     * This field is mapped on the database column "TYLE_TT" ( type "INT", NotNull : true ) 
     * @param TYLE_TT
     */
    public void setTYLE_TT( Integer TYLE_TT )
    {
        this.MUC_HUONG = TYLE_TT;
    }
    /**
     * Get the "tyleTt" field value
     * This field is mapped on the database column "TYLE_TT" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getTYLE_TT()
    {
        return this.MUC_HUONG;
    }

    //--- DATABASE MAPPING : CUR_DATE ( TIMESTAMP ) 
    /**
     * Set the "CUR_DATE" field value
     * This field is mapped on the database column "CUR_DATE" ( type "TIMESTAMP", NotNull : false ) 
     * @param CUR_DATE
     */
    public void setCUR_DATE( Date CUR_DATE )
    {
        this.CUR_DATE = CUR_DATE;
    }
    /**
     * Get the "curDate" field value
     * This field is mapped on the database column "CUR_DATE" ( type "TIMESTAMP", NotNull : false ) 
     * @return the field value
     */
    public Date getCUR_DATE()
    {
        return this.CUR_DATE;
    }

    //--- DATABASE MAPPING : TYP ( INT ) 
    /**
     * Set the "TYP" field value
     * This field is mapped on the database column "TYP" ( type "INT", NotNull : false ) 
     * @param TYP
     */
    public void setTYP( Integer TYP )
    {
        this.TYP = TYP;
    }
    /**
     * Get the "typ" field value
     * This field is mapped on the database column "TYP" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getTYP()
    {
        return this.TYP;
    }

    //--- DATABASE MAPPING : THANHTOAN ( INT ) 
    /**
     * Set the "THANHTOAN" field value
     * This field is mapped on the database column "THANHTOAN" ( type "INT", NotNull : false ) 
     * @param THANHTOAN
     */
    public void setTHANHTOAN( Integer THANHTOAN )
    {
        this.THANHTOAN = THANHTOAN;
    }
    /**
     * Get the "thanhtoan" field value
     * This field is mapped on the database column "THANHTOAN" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getTHANHTOAN()
    {
        return this.THANHTOAN;
    }

    //--- DATABASE MAPPING : NV_ID ( INT ) 
    /**
     * Set the "NV_ID" field value
     * This field is mapped on the database column "NV_ID" ( type "INT", NotNull : false ) 
     * @param NV_ID
     */
    public void setNV_ID( Integer NV_ID )
    {
        this.NV_ID = NV_ID;
    }
    /**
     * Get the "nvId" field value
     * This field is mapped on the database column "NV_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getNV_ID()
    {
        return this.NV_ID;
    }

    //--- DATABASE MAPPING : NV_NAME ( VARCHAR ) 
    /**
     * Set the "NV_NAME" field value
     * This field is mapped on the database column "NV_NAME" ( type "VARCHAR", NotNull : false ) 
     * @param NV_NAME
     */
    public void setNV_NAME( String NV_NAME )
    {
        this.NV_NAME = NV_NAME;
    }
    /**
     * Get the "nvName" field value
     * This field is mapped on the database column "NV_NAME" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getNV_NAME()
    {
        return this.NV_NAME;
    }

    //--- DATABASE MAPPING : NHOM_DV ( INT ) 
    /**
     * Set the "NHOM_DV" field value
     * This field is mapped on the database column "NHOM_DV" ( type "INT", NotNull : false ) 
     * @param NHOM_DV
     */
    public void setNHOM_DV( Integer NHOM_DV )
    {
        this.NHOM_DV = NHOM_DV;
    }
    /**
     * Get the "nhomDv" field value
     * This field is mapped on the database column "NHOM_DV" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getNHOM_DV()
    {
        return this.NHOM_DV;
    }

    //--- DATABASE MAPPING : STS ( INT ) 
    /**
     * Set the "STS" field value
     * This field is mapped on the database column "STS" ( type "INT", NotNull : false ) 
     * @param STS
     */
    public void setSTS( Integer STS )
    {
        this.STS = STS;
    }
    /**
     * Get the "sts" field value
     * This field is mapped on the database column "STS" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getSTS()
    {
        return this.STS;
    }



/*
 * CRUD functions
 */
    public static DvChitiet load(String DVCT_ID) {
    	Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
			String sql = "select * from dv_chitiet where DVCT_ID=:DVCT_ID";
			logger.debug(sql);
			DvChitiet obj = connection
					.createQuery(
							sql,
							true)
					.addParameter("DVCT_ID", DVCT_ID)
					.executeAndFetchFirst( DvChitiet.class);
            logger.info(obj);
            logger.debug("Load "+obj);
            return obj;
		} catch (Exception t) {
            logger.error("Load Error: ID="+DVCT_ID +"\nException=\n"+ t);
			throw new RuntimeException("LOAD [DvChitiet]. ERROR: "+t.getMessage(), t);
		}
    }
    
    public static DvChitiet load(Integer DVCT_ID) {
    	Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
			String sql = "select * from dv_chitiet where DVCT_ID=:DVCT_ID";
			logger.debug(sql);
			DvChitiet obj = connection
					.createQuery(
							sql,
							true)
					.addParameter("DVCT_ID", DVCT_ID)
					.executeAndFetchFirst( DvChitiet.class);
            logger.info(obj);
            logger.debug("Load "+obj);
            return obj;
		} catch (Exception t) {
            logger.error("Load Error: ID="+DVCT_ID +"\nException=\n"+ t);
			throw new RuntimeException("LOAD [DvChitiet]. ERROR: "+t.getMessage(), t);
		}
    }
    
    public String toString(){
    	String strData = "dv_chitiet "
    			+" DVCT_ID = " + DVCT_ID                + "; BN_ID = " + BN_ID
                + "; MA_LK = " + MA_LK
                + "; DV_ID = " + DV_ID
                + "; MA_DICH_VU = " + MA_DICH_VU
                + "; MA_VAT_TU = " + MA_VAT_TU
                + "; MA_NHOM = " + MA_NHOM
                + "; GOI_VTYT = " + GOI_VTYT
                + "; TEN_VAT_TU = " + TEN_VAT_TU
                + "; TEN_DICH_VU = " + TEN_DICH_VU
                + "; DON_VI_TINH = " + DON_VI_TINH
                + "; PHAM_VI = " + PHAM_VI
                + "; SO_LUONG = " + SO_LUONG
                + "; DON_GIA = " + DON_GIA
                + "; DON_GIA2 = " + DON_GIA2
                + "; TT_THAU = " + TT_THAU
                + "; THANH_TIEN = " + THANH_TIEN
                + "; THANH_TIEN2 = " + THANH_TIEN2
                + "; T_TRANTT = " + T_TRANTT
                + "; MUC_HUONG = " + TYLE_TT
                + "; T_NGUONKHAC = " + T_NGUONKHAC
                + "; TT_BHTT = " + TT_BHTT
                + "; TT_BNTT = " + TT_BNTT
                + "; T_BNCCT = " + T_BNCCT
                + "; T_NGOAIDS = " + T_NGOAIDS
                + "; MA_GIUONG = " + MA_GIUONG
                + "; MA_KHOA = " + MA_KHOA
                + "; MA_BAC_SI = " + MA_BAC_SI
                + "; MA_BENH = " + MA_BENH
                + "; NGAY_YL = " + NGAY_YL
                + "; NGAY_KQ = " + NGAY_KQ
                + "; MA_PTTT = " + MA_PTTT
                + "; TYLE_TT = " + MUC_HUONG
                + "; CUR_DATE = " + CUR_DATE
                + "; TYP = " + TYP
                + "; THANHTOAN = " + THANHTOAN
                + "; NV_ID = " + NV_ID
                + "; NV_NAME = " + NV_NAME
                + "; NHOM_DV = " + NHOM_DV
                + "; STS = " + STS
    			;
    	return strData;
    }
    
    public void insert() {
		//
    	if( DVCT_ID !=null){
			// Update 
            update();
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.INSERT, "dv_chitiet")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE INSERT RIGHT for table dv_chitiet");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);

            logger.info("Insert [dv_chitiet] BEGIN: "+ this.toString());

            String sql = "insert into dv_chitiet (BN_ID, MA_LK, DV_ID, MA_DICH_VU, MA_VAT_TU, MA_NHOM, GOI_VTYT, TEN_VAT_TU, TEN_DICH_VU, DON_VI_TINH, PHAM_VI, SO_LUONG, DON_GIA, DON_GIA2, TT_THAU, THANH_TIEN, THANH_TIEN2, T_TRANTT, MUC_HUONG, T_NGUONKHAC, TT_BHTT, TT_BNTT, T_BNCCT, T_NGOAIDS, MA_GIUONG, MA_KHOA, MA_BAC_SI, MA_BENH, NGAY_YL, NGAY_KQ, MA_PTTT, TYLE_TT, CUR_DATE, TYP, THANHTOAN, NV_ID, NV_NAME, NHOM_DV,  STS) values(:BN_ID, :MA_LK, :DV_ID, :MA_DICH_VU, :MA_VAT_TU, :MA_NHOM, :GOI_VTYT, :TEN_VAT_TU, :TEN_DICH_VU, :DON_VI_TINH, :PHAM_VI, :SO_LUONG, :DON_GIA, :DON_GIA2, :TT_THAU, :THANH_TIEN, :THANH_TIEN2, :T_TRANTT, :MUC_HUONG, :T_NGUONKHAC, :TT_BHTT, :TT_BNTT, :T_BNCCT, :T_NGOAIDS, :MA_GIUONG, :MA_KHOA, :MA_BAC_SI, :MA_BENH, :NGAY_YL, :NGAY_KQ, :MA_PTTT, :TYLE_TT, :CUR_DATE, :TYP, :THANHTOAN, :NV_ID, :NV_NAME, :NHOM_DV,  0)";
                            			int createdId = connection
                            					.createQuery(
							sql,
							true)
                        .addParameter("BN_ID", this.BN_ID)
                            .addParameter("MA_LK", this.MA_LK)
                            .addParameter("DV_ID", this.DV_ID)
                            .addParameter("MA_DICH_VU", this.MA_DICH_VU)
                            .addParameter("MA_VAT_TU", this.MA_VAT_TU)
                            .addParameter("MA_NHOM", this.MA_NHOM)
                            .addParameter("GOI_VTYT", this.GOI_VTYT)
                            .addParameter("TEN_VAT_TU", this.TEN_VAT_TU)
                            .addParameter("TEN_DICH_VU", this.TEN_DICH_VU)
                            .addParameter("DON_VI_TINH", this.DON_VI_TINH)
                            .addParameter("PHAM_VI", this.PHAM_VI)
                            .addParameter("SO_LUONG", this.SO_LUONG)
                            .addParameter("DON_GIA", this.DON_GIA)
                            .addParameter("DON_GIA2", this.DON_GIA2)
                            .addParameter("TT_THAU", this.TT_THAU)
                            .addParameter("THANH_TIEN", this.THANH_TIEN)
                            .addParameter("THANH_TIEN2", this.THANH_TIEN2)
                            .addParameter("T_TRANTT", this.T_TRANTT)
                            .addParameter("MUC_HUONG", this.TYLE_TT)
                            .addParameter("T_NGUONKHAC", this.T_NGUONKHAC)
                            .addParameter("TT_BHTT", this.TT_BHTT)
                            .addParameter("TT_BNTT", this.TT_BNTT)
                            .addParameter("T_BNCCT", this.T_BNCCT)
                            .addParameter("T_NGOAIDS", this.T_NGOAIDS)
                            .addParameter("MA_GIUONG", this.MA_GIUONG)
                            .addParameter("MA_KHOA", this.MA_KHOA)
                            .addParameter("MA_BAC_SI", this.MA_BAC_SI)
                            .addParameter("MA_BENH", this.MA_BENH)
                            .addParameter("NGAY_YL", this.NGAY_YL)
                            .addParameter("NGAY_KQ", this.NGAY_KQ)
                            .addParameter("MA_PTTT", this.MA_PTTT)
                            .addParameter("TYLE_TT", this.MUC_HUONG)
                            .addParameter("CUR_DATE", this.CUR_DATE)
                            .addParameter("TYP", this.TYP)
                            .addParameter("THANHTOAN", this.THANHTOAN)
                            .addParameter("NV_ID", this.NV_ID)
                            .addParameter("NV_NAME", this.NV_NAME)
                            .addParameter("NHOM_DV", this.NHOM_DV)
        					.executeUpdate()
                                                .getKey(Integer.class);
                            					
            logger.info("Add OK: NewID="+createdId);
            logger.info("Add OK [dv_chitiet] debug: "+toString());
            // Set KEYID DVCT_ID = newID
                            DVCT_ID = createdId;
                            			// Save log
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "New dv_chitiet. ID="+DVCT_ID)
                    .addParameter("dbtable", "dv_chitiet")
                    .addParameter("fieldid", DVCT_ID)
					.addParameter("actionid", 1)
					.executeUpdate();
            logger.info("Add [dv_chitiet] OK: NewID="+createdId);
            logger.info("Add [dv_chitiet] OK: Data="+this.toString());
		} catch (Exception t) {
            logger.error("Add [dv_chitiet] Error: "+"\nException=\n"+ t);
			throw new RuntimeException("ADD [dv_chitiet]. ERROR: "+t.getMessage(), t);
		}
	}
    
    public void update() {
		//
    	if(DVCT_ID==null){
            insert();
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.UPDATE, "dv_chitiet")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE UPDATE RIGHT for table dv_chitiet");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);
            DvChitiet temp = DvChitiet.load(this.DVCT_ID);
            if(temp!=null){
            	logger.info("Begin Update [dv_chitiet]: "+temp.toString());
            }
            logger.info("Update [dv_chitiet] BEGIN: "+ this.toString());
			//
			String sql = "update dv_chitiet set BN_ID=:BN_ID, MA_LK=:MA_LK, DV_ID=:DV_ID, MA_DICH_VU=:MA_DICH_VU, MA_VAT_TU=:MA_VAT_TU, MA_NHOM=:MA_NHOM, GOI_VTYT=:GOI_VTYT, TEN_VAT_TU=:TEN_VAT_TU, TEN_DICH_VU=:TEN_DICH_VU, DON_VI_TINH=:DON_VI_TINH, PHAM_VI=:PHAM_VI, SO_LUONG=:SO_LUONG, DON_GIA=:DON_GIA, DON_GIA2=:DON_GIA2, TT_THAU=:TT_THAU, THANH_TIEN=:THANH_TIEN, THANH_TIEN2=:THANH_TIEN2, T_TRANTT=:T_TRANTT, MUC_HUONG=:MUC_HUONG, T_NGUONKHAC=:T_NGUONKHAC, TT_BHTT=:TT_BHTT, TT_BNTT=:TT_BNTT, T_BNCCT=:T_BNCCT, T_NGOAIDS=:T_NGOAIDS, MA_GIUONG=:MA_GIUONG, MA_KHOA=:MA_KHOA, MA_BAC_SI=:MA_BAC_SI, MA_BENH=:MA_BENH, NGAY_YL=:NGAY_YL, NGAY_KQ=:NGAY_KQ, MA_PTTT=:MA_PTTT, TYLE_TT=:TYLE_TT, CUR_DATE=:CUR_DATE, TYP=:TYP, THANHTOAN=:THANHTOAN, NV_ID=:NV_ID, NV_NAME=:NV_NAME, NHOM_DV=:NHOM_DV, STS=:STS where DVCT_ID=:DVCT_ID";
			connection
					.createQuery(
							sql,
							true)
                    .addParameter("BN_ID", this.BN_ID)
                    .addParameter("MA_LK", this.MA_LK)
                    .addParameter("DV_ID", this.DV_ID)
                    .addParameter("MA_DICH_VU", this.MA_DICH_VU)
                    .addParameter("MA_VAT_TU", this.MA_VAT_TU)
                    .addParameter("MA_NHOM", this.MA_NHOM)
                    .addParameter("GOI_VTYT", this.GOI_VTYT)
                    .addParameter("TEN_VAT_TU", this.TEN_VAT_TU)
                    .addParameter("TEN_DICH_VU", this.TEN_DICH_VU)
                    .addParameter("DON_VI_TINH", this.DON_VI_TINH)
                    .addParameter("PHAM_VI", this.PHAM_VI)
                    .addParameter("SO_LUONG", this.SO_LUONG)
                    .addParameter("DON_GIA", this.DON_GIA)
                    .addParameter("DON_GIA2", this.DON_GIA2)
                    .addParameter("TT_THAU", this.TT_THAU)
                    .addParameter("THANH_TIEN", this.THANH_TIEN)
                    .addParameter("THANH_TIEN2", this.THANH_TIEN2)
                    .addParameter("T_TRANTT", this.T_TRANTT)
                    .addParameter("MUC_HUONG", this.TYLE_TT)
                    .addParameter("T_NGUONKHAC", this.T_NGUONKHAC)
                    .addParameter("TT_BHTT", this.TT_BHTT)
                    .addParameter("TT_BNTT", this.TT_BNTT)
                    .addParameter("T_BNCCT", this.T_BNCCT)
                    .addParameter("T_NGOAIDS", this.T_NGOAIDS)
                    .addParameter("MA_GIUONG", this.MA_GIUONG)
                    .addParameter("MA_KHOA", this.MA_KHOA)
                    .addParameter("MA_BAC_SI", this.MA_BAC_SI)
                    .addParameter("MA_BENH", this.MA_BENH)
                    .addParameter("NGAY_YL", this.NGAY_YL)
                    .addParameter("NGAY_KQ", this.NGAY_KQ)
                    .addParameter("MA_PTTT", this.MA_PTTT)
                    .addParameter("TYLE_TT", this.MUC_HUONG)
                    .addParameter("CUR_DATE", this.CUR_DATE)
                    .addParameter("TYP", this.TYP)
                    .addParameter("THANHTOAN", this.THANHTOAN)
                    .addParameter("NV_ID", this.NV_ID)
                    .addParameter("NV_NAME", this.NV_NAME)
                    .addParameter("NHOM_DV", this.NHOM_DV)
                    .addParameter("STS", this.STS)
					.addParameter("DVCT_ID", this.DVCT_ID)
					.executeUpdate();
            logger.info("Update [dv_chitiet] OK: ID="+DVCT_ID);
            logger.info("End   Update [dv_chitiet]: "+toString());
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "Update dv_chitiet. ID="+DVCT_ID)
                    .addParameter("dbtable", "dv_chitiet")
                    .addParameter("fieldid", DVCT_ID)
					.addParameter("actionid", 2)
					.executeUpdate();
		} catch (Exception t) {
			logger.error("Update [dv_chitiet] Error: ID=["+DVCT_ID +"]."+"\nException=\n"+ t);
			throw new RuntimeException("Update [dv_chitiet]. ERROR: "+t.getMessage(), t);
		}
	}
    
    
    public void delete() {
		//
    	if(DVCT_ID==null){
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.DELETE, "dv_chitiet")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE DELETE RIGHT for table dv_chitiet");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);
            logger.error("Update Row [dv_chitiet] BEGIN: ID=["+DVCT_ID +"]. " + this.toString());
			String sql = "update dv_chitiet set STS=:STS where DVCT_ID=:DVCT_ID";
			connection
					.createQuery(
							sql,
							true)
					.addParameter("STS", DbHelper.DELETE_STATUS)
					.addParameter("DVCT_ID", this.DVCT_ID)
					.executeUpdate();
			logger.error("Delete [dv_chitiet] OK: ID=["+DVCT_ID +"].");
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "Update dv_chitiet. ID="+DVCT_ID)
                    .addParameter("dbtable", "dv_chitiet")
                    .addParameter("fieldid", DVCT_ID)
					.addParameter("actionid", 3)
					.executeUpdate();
		} catch (Exception t) {
			logger.error("Delete [dv_chitiet] Error: ID=["+DVCT_ID +"]."+"\nException=\n"+ t);
			throw new RuntimeException("Delete [dv_chitiet]. ID=["+DVCT_ID + " ERROR: "+t.getMessage(), t);
		}
	}
    
	public void deleteRow() {
		//
    	if(DVCT_ID==null){
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.DELETE, "dv_chitiet")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE DELETE RIGHT for table dv_chitiet");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);
            logger.error("Delete Row [dv_chitiet] BEGIN: ID=["+DVCT_ID +"]. " + this.toString());
			String sql = "delete from dv_chitiet where DVCT_ID=:DVCT_ID";
			connection
					.createQuery(
							sql,
							true)
					.addParameter("DVCT_ID", this.DVCT_ID)
					.executeUpdate();
			logger.error("Delete Row [dv_chitiet] OK: ID=["+DVCT_ID +"].");
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "Update dv_chitiet. ID="+DVCT_ID)
                    .addParameter("dbtable", "dv_chitiet")
                    .addParameter("fieldid", DVCT_ID)
					.addParameter("actionid", 4)
					.executeUpdate();
		} catch (Exception t) {
			logger.error("Delete [dv_chitiet] Error: ID=["+DVCT_ID +"]."+"\nException=\n"+ t);
			throw new RuntimeException("Delete [dv_chitiet]. ID=["+DVCT_ID + " ERROR: "+t.getMessage(), t);
		}
	}
    
    public String getIndex(int idx){
        switch(idx){
            case 0:
                // java.lang.Integer   
                if(this.BN_ID!=null)
                    return this.BN_ID.toString();
                else
                    return "N/A";
            case 1:
                // java.lang.Integer   
                if(this.MA_LK!=null)
                    return this.MA_LK.toString();
                else
                    return "N/A";
            case 2:
                // java.lang.Integer   
                if(this.DV_ID!=null)
                    return this.DV_ID.toString();
                else
                    return "N/A";
            case 3:
                // java.lang.String    
                if(this.MA_DICH_VU!=null)
                    return this.MA_DICH_VU.toString();
                else
                    return "N/A";
            case 4:
                // java.lang.String    
                if(this.MA_VAT_TU!=null)
                    return this.MA_VAT_TU.toString();
                else
                    return "N/A";
            case 5:
                // java.lang.Integer   
                if(this.MA_NHOM!=null)
                    return this.MA_NHOM.toString();
                else
                    return "N/A";
            case 6:
                // java.lang.String    
                if(this.GOI_VTYT!=null)
                    return this.GOI_VTYT.toString();
                else
                    return "N/A";
            case 7:
                // java.lang.String    
                if(this.TEN_VAT_TU!=null)
                    return this.TEN_VAT_TU.toString();
                else
                    return "N/A";
            case 8:
                // java.lang.String    
                if(this.TEN_DICH_VU!=null)
                    return this.TEN_DICH_VU.toString();
                else
                    return "N/A";
            case 9:
                // java.lang.String    
                if(this.DON_VI_TINH!=null)
                    return this.DON_VI_TINH.toString();
                else
                    return "N/A";
            case 10:
                // java.lang.Integer   
                if(this.PHAM_VI!=null)
                    return this.PHAM_VI.toString();
                else
                    return "N/A";
            case 11:
                // java.lang.Integer   
                if(this.SO_LUONG!=null)
                    return this.SO_LUONG.toString();
                else
                    return "N/A";
            case 12:
                // java.lang.Integer   
                if(this.DON_GIA!=null)
                    return this.DON_GIA.toString();
                else
                    return "N/A";
            case 13:
                // java.lang.Integer   
                if(this.DON_GIA2!=null)
                    return this.DON_GIA2.toString();
                else
                    return "N/A";
            case 14:
                // java.lang.String    
                if(this.TT_THAU!=null)
                    return this.TT_THAU.toString();
                else
                    return "N/A";
            case 15:
                // java.lang.Integer   
                if(this.THANH_TIEN!=null)
                    return this.THANH_TIEN.toString();
                else
                    return "N/A";
            case 16:
                // java.lang.Integer   
                if(this.THANH_TIEN2!=null)
                    return this.THANH_TIEN2.toString();
                else
                    return "N/A";
            case 17:
                // java.lang.Integer   
                if(this.T_TRANTT!=null)
                    return this.T_TRANTT.toString();
                else
                    return "N/A";
            case 18:
                // java.lang.Integer   
                if(this.TYLE_TT!=null)
                    return this.TYLE_TT.toString();
                else
                    return "N/A";
            case 19:
                // java.lang.Integer   
                if(this.T_NGUONKHAC!=null)
                    return this.T_NGUONKHAC.toString();
                else
                    return "N/A";
            case 20:
                // java.lang.Integer   
                if(this.TT_BHTT!=null)
                    return this.TT_BHTT.toString();
                else
                    return "N/A";
            case 21:
                // java.lang.Integer   
                if(this.TT_BNTT!=null)
                    return this.TT_BNTT.toString();
                else
                    return "N/A";
            case 22:
                // java.lang.Integer   
                if(this.T_BNCCT!=null)
                    return this.T_BNCCT.toString();
                else
                    return "N/A";
            case 23:
                // java.lang.Integer   
                if(this.T_NGOAIDS!=null)
                    return this.T_NGOAIDS.toString();
                else
                    return "N/A";
            case 24:
                // java.lang.String    
                if(this.MA_GIUONG!=null)
                    return this.MA_GIUONG.toString();
                else
                    return "N/A";
            case 25:
                // java.lang.String    
                if(this.MA_KHOA!=null)
                    return this.MA_KHOA.toString();
                else
                    return "N/A";
            case 26:
                // java.lang.String    
                if(this.MA_BAC_SI!=null)
                    return this.MA_BAC_SI.toString();
                else
                    return "N/A";
            case 27:
                // java.lang.String    
                if(this.MA_BENH!=null)
                    return this.MA_BENH.toString();
                else
                    return "N/A";
            case 28:
                // java.lang.String    
                if(this.NGAY_YL!=null)
                    return this.NGAY_YL.toString();
                else
                    return "N/A";
            case 29:
                // java.lang.String    
                if(this.NGAY_KQ!=null)
                    return this.NGAY_KQ.toString();
                else
                    return "N/A";
            case 30:
                // java.lang.Integer   
                if(this.MA_PTTT!=null)
                    return this.MA_PTTT.toString();
                else
                    return "N/A";
            case 31:
                // java.lang.Integer   
                if(this.MUC_HUONG!=null)
                    return this.MUC_HUONG.toString();
                else
                    return "N/A";
            case 32:
                // java.lang.Date      
                if(this.CUR_DATE!=null)
                    return this.CUR_DATE.toString();
                else
                    return "N/A";
            case 33:
                // java.lang.Integer   
                if(this.TYP!=null)
                    return this.TYP.toString();
                else
                    return "N/A";
            case 34:
                // java.lang.Integer   
                if(this.THANHTOAN!=null)
                    return this.THANHTOAN.toString();
                else
                    return "N/A";
            case 35:
                // java.lang.Integer   
                if(this.NV_ID!=null)
                    return this.NV_ID.toString();
                else
                    return "N/A";
            case 36:
                // java.lang.String    
                if(this.NV_NAME!=null)
                    return this.NV_NAME.toString();
                else
                    return "N/A";
            case 37:
                // java.lang.Integer   
                if(this.NHOM_DV!=null)
                    return this.NHOM_DV.toString();
                else
                    return "N/A";
            case 38:
                // java.lang.Integer   
                if(this.STS!=null)
                    return this.STS.toString();
                else
                    return "N/A";
            default:
        }
        return "";
    }
}