/*
 * Java bean class for entity table nhap_thuoc 
 * Created on 21 Oct 2017 ( Date ISO 2017-10-21 - Time 17:11:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 * template update by NEO
 */

package com.model.dao;

import java.io.Serializable;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.sql2o.Connection;
import com.DbHelper;

import java.util.Date;

/**
 * Entity bean for table "nhap_thuoc"
 * 
 * @author Telosys Tools Generator
 *
 */
public class NhapThuoc implements Serializable
{
    static Logger logger = LogManager.getLogger(NhapThuoc.class.getName());
    private static final long serialVersionUID = 1L;

    public Integer    NT_ID ; // Primary Key

    public Integer    V_ID ;
    public Integer    KHO_ID ;
    public String     VENDOR_NAME ;
    public Date       NGAY_NHAP ;
    public String     TENKHO ;
    public String     HOADON ;
    public Integer    TONGCONG ;
    public Integer    STS ;

    /**
     * Default constructor
     */
    public NhapThuoc()
    {
        super();
        // Set default value 
this.V_ID = 0;                         // data type = Integer   
this.KHO_ID = 0;                         // data type = Integer   
this.VENDOR_NAME = "";//String.format("%255.255s", "VENDOR_NAME").trim(); // data type = String     255
this.NGAY_NHAP = new java.util.Date();      // data type = Date      
this.TENKHO = "";//String.format("%32.32s", "TENKHO").trim(); // data type = String     32
this.HOADON = "";//String.format("%32.32s", "HOADON").trim(); // data type = String     32
this.TONGCONG = 0;                         // data type = Integer   
this.STS = 0;                         // data type = Integer   
        // End Set default value 
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "ntId" field value
     * This field is mapped on the database column "NT_ID" ( type "INT", NotNull : true ) 
     * @param NT_ID
     */
	public void setNT_ID( Integer NT_ID )
    {
        this.NT_ID = NT_ID ;
    }
    /**
     * Get the "NT_ID" field value
     * This field is mapped on the database column "NT_ID" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getNT_ID()
    {
        return this.NT_ID;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : V_ID ( INT ) 
    /**
     * Set the "V_ID" field value
     * This field is mapped on the database column "V_ID" ( type "INT", NotNull : true ) 
     * @param V_ID
     */
    public void setV_ID( Integer V_ID )
    {
        this.V_ID = V_ID;
    }
    /**
     * Get the "vId" field value
     * This field is mapped on the database column "V_ID" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getV_ID()
    {
        return this.V_ID;
    }

    //--- DATABASE MAPPING : KHO_ID ( INT ) 
    /**
     * Set the "KHO_ID" field value
     * This field is mapped on the database column "KHO_ID" ( type "INT", NotNull : false ) 
     * @param KHO_ID
     */
    public void setKHO_ID( Integer KHO_ID )
    {
        this.KHO_ID = KHO_ID;
    }
    /**
     * Get the "khoId" field value
     * This field is mapped on the database column "KHO_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getKHO_ID()
    {
        return this.KHO_ID;
    }

    //--- DATABASE MAPPING : VENDOR_NAME ( VARCHAR ) 
    /**
     * Set the "VENDOR_NAME" field value
     * This field is mapped on the database column "VENDOR_NAME" ( type "VARCHAR", NotNull : true ) 
     * @param VENDOR_NAME
     */
    public void setVENDOR_NAME( String VENDOR_NAME )
    {
        this.VENDOR_NAME = VENDOR_NAME;
    }
    /**
     * Get the "vendorName" field value
     * This field is mapped on the database column "VENDOR_NAME" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getVENDOR_NAME()
    {
        return this.VENDOR_NAME;
    }

    //--- DATABASE MAPPING : NGAY_NHAP ( TIMESTAMP ) 
    /**
     * Set the "NGAY_NHAP" field value
     * This field is mapped on the database column "NGAY_NHAP" ( type "TIMESTAMP", NotNull : true ) 
     * @param NGAY_NHAP
     */
    public void setNGAY_NHAP( Date NGAY_NHAP )
    {
        this.NGAY_NHAP = NGAY_NHAP;
    }
    /**
     * Get the "ngayNhap" field value
     * This field is mapped on the database column "NGAY_NHAP" ( type "TIMESTAMP", NotNull : true ) 
     * @return the field value
     */
    public Date getNGAY_NHAP()
    {
        return this.NGAY_NHAP;
    }

    //--- DATABASE MAPPING : TENKHO ( VARCHAR ) 
    /**
     * Set the "TENKHO" field value
     * This field is mapped on the database column "TENKHO" ( type "VARCHAR", NotNull : false ) 
     * @param TENKHO
     */
    public void setTENKHO( String TENKHO )
    {
        this.TENKHO = TENKHO;
    }
    /**
     * Get the "tenkho" field value
     * This field is mapped on the database column "TENKHO" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getTENKHO()
    {
        return this.TENKHO;
    }

    //--- DATABASE MAPPING : HOADON ( VARCHAR ) 
    /**
     * Set the "HOADON" field value
     * This field is mapped on the database column "HOADON" ( type "VARCHAR", NotNull : true ) 
     * @param HOADON
     */
    public void setHOADON( String HOADON )
    {
        this.HOADON = HOADON;
    }
    /**
     * Get the "hoadon" field value
     * This field is mapped on the database column "HOADON" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getHOADON()
    {
        return this.HOADON;
    }

    //--- DATABASE MAPPING : TONGCONG ( INT ) 
    /**
     * Set the "TONGCONG" field value
     * This field is mapped on the database column "TONGCONG" ( type "INT", NotNull : true ) 
     * @param TONGCONG
     */
    public void setTONGCONG( Integer TONGCONG )
    {
        this.TONGCONG = TONGCONG;
    }
    /**
     * Get the "tongcong" field value
     * This field is mapped on the database column "TONGCONG" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getTONGCONG()
    {
        return this.TONGCONG;
    }

    //--- DATABASE MAPPING : STS ( INT ) 
    /**
     * Set the "STS" field value
     * This field is mapped on the database column "STS" ( type "INT", NotNull : true ) 
     * @param STS
     */
    public void setSTS( Integer STS )
    {
        this.STS = STS;
    }
    /**
     * Get the "sts" field value
     * This field is mapped on the database column "STS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getSTS()
    {
        return this.STS;
    }



/*
 * CRUD functions
 */
    public static NhapThuoc load(String NT_ID) {
    	Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
			String sql = "select * from nhap_thuoc where NT_ID=:NT_ID";
			logger.debug(sql);
			NhapThuoc obj = connection
					.createQuery(
							sql,
							true)
					.addParameter("NT_ID", NT_ID)
					.executeAndFetchFirst( NhapThuoc.class);
            logger.info(obj);
            logger.debug("Load "+obj);
            return obj;
		} catch (Exception t) {
            logger.error("Load Error: ID="+NT_ID +"\nException=\n"+ t);
			throw new RuntimeException("LOAD [NhapThuoc]. ERROR: "+t.getMessage(), t);
		}
    }
    
    public static NhapThuoc load(Integer NT_ID) {
    	Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
			String sql = "select * from nhap_thuoc where NT_ID=:NT_ID";
			logger.debug(sql);
			NhapThuoc obj = connection
					.createQuery(
							sql,
							true)
					.addParameter("NT_ID", NT_ID)
					.executeAndFetchFirst( NhapThuoc.class);
            logger.info(obj);
            logger.debug("Load "+obj);
            return obj;
		} catch (Exception t) {
            logger.error("Load Error: ID="+NT_ID +"\nException=\n"+ t);
			throw new RuntimeException("LOAD [NhapThuoc]. ERROR: "+t.getMessage(), t);
		}
    }
    
    public String toString(){
    	String strData = "nhap_thuoc "
    			+" NT_ID = " + NT_ID                + "; V_ID = " + V_ID
                + "; KHO_ID = " + KHO_ID
                + "; VENDOR_NAME = " + VENDOR_NAME
                + "; NGAY_NHAP = " + NGAY_NHAP
                + "; TENKHO = " + TENKHO
                + "; HOADON = " + HOADON
                + "; TONGCONG = " + TONGCONG
                + "; STS = " + STS
    			;
    	return strData;
    }
    
    public void insert() {
		//
    	if( NT_ID !=null){
			// Update 
            update();
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.INSERT, "nhap_thuoc")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE INSERT RIGHT for table nhap_thuoc");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);

            String sql = "insert into nhap_thuoc (V_ID, KHO_ID, VENDOR_NAME, NGAY_NHAP, TENKHO, HOADON, TONGCONG,  STS) values(:V_ID, :KHO_ID, :VENDOR_NAME, :NGAY_NHAP, :TENKHO, :HOADON, :TONGCONG,  0)";
                            			int createdId = connection
                            					.createQuery(
							sql,
							true)
                        .addParameter("V_ID", this.V_ID)
                            .addParameter("KHO_ID", this.KHO_ID)
                            .addParameter("VENDOR_NAME", this.VENDOR_NAME)
                            .addParameter("NGAY_NHAP", this.NGAY_NHAP)
                            .addParameter("TENKHO", this.TENKHO)
                            .addParameter("HOADON", this.HOADON)
                            .addParameter("TONGCONG", this.TONGCONG)
        					.executeUpdate()
                                                .getKey(Integer.class);
                            					
            logger.info("Add OK: NewID="+createdId);
            logger.info("Add OK [nhap_thuoc] debug: "+toString());
            // Set KEYID NT_ID = newID
                            NT_ID = createdId;
                            			// Save log
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "New nhap_thuoc. ID="+NT_ID)
                    .addParameter("dbtable", "nhap_thuoc")
                    .addParameter("fieldid", NT_ID)
					.addParameter("actionid", 1)
					.executeUpdate();
            logger.info("Add [nhap_thuoc] OK: NewID="+createdId);
		} catch (Exception t) {
            logger.error("Add [nhap_thuoc] Error: "+"\nException=\n"+ t);
			throw new RuntimeException("ADD [nhap_thuoc]. ERROR: "+t.getMessage(), t);
		}
	}
    
    public void update() {
		//
    	if(NT_ID==null){
            insert();
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.UPDATE, "nhap_thuoc")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE UPDATE RIGHT for table nhap_thuoc");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);
			String sql = "update nhap_thuoc set V_ID=:V_ID, KHO_ID=:KHO_ID, VENDOR_NAME=:VENDOR_NAME, NGAY_NHAP=:NGAY_NHAP, TENKHO=:TENKHO, HOADON=:HOADON, TONGCONG=:TONGCONG, STS=:STS where NT_ID=:NT_ID";
			connection
					.createQuery(
							sql,
							true)
                    .addParameter("V_ID", this.V_ID)
                    .addParameter("KHO_ID", this.KHO_ID)
                    .addParameter("VENDOR_NAME", this.VENDOR_NAME)
                    .addParameter("NGAY_NHAP", this.NGAY_NHAP)
                    .addParameter("TENKHO", this.TENKHO)
                    .addParameter("HOADON", this.HOADON)
                    .addParameter("TONGCONG", this.TONGCONG)
                    .addParameter("STS", this.STS)
					.addParameter("NT_ID", this.NT_ID)
					.executeUpdate();
            logger.info("Update [nhap_thuoc] OK: ID="+NT_ID);
            logger.info("Update [nhap_thuoc] debug: "+toString());
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "Update nhap_thuoc. ID="+NT_ID)
                    .addParameter("dbtable", "nhap_thuoc")
                    .addParameter("fieldid", NT_ID)
					.addParameter("actionid", 2)
					.executeUpdate();
		} catch (Exception t) {
			logger.error("Update [nhap_thuoc] Error: ID=["+NT_ID +"]."+"\nException=\n"+ t);
			throw new RuntimeException("Update [nhap_thuoc]. ERROR: "+t.getMessage(), t);
		}
	}
    
    
    public void delete() {
		//
    	if(NT_ID==null){
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.DELETE, "nhap_thuoc")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE DELETE RIGHT for table nhap_thuoc");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);
			String sql = "update nhap_thuoc set STS=:STS where NT_ID=:NT_ID";
			connection
					.createQuery(
							sql,
							true)
					.addParameter("STS", DbHelper.DELETE_STATUS)
					.addParameter("NT_ID", this.NT_ID)
					.executeUpdate();
			logger.error("Delete [nhap_thuoc] OK: ID=["+NT_ID +"].");
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "Update nhap_thuoc. ID="+NT_ID)
                    .addParameter("dbtable", "nhap_thuoc")
                    .addParameter("fieldid", NT_ID)
					.addParameter("actionid", 3)
					.executeUpdate();
		} catch (Exception t) {
			logger.error("Delete [nhap_thuoc] Error: ID=["+NT_ID +"]."+"\nException=\n"+ t);
			throw new RuntimeException("Delete [nhap_thuoc]. ID=["+NT_ID + " ERROR: "+t.getMessage(), t);
		}
	}
    
	public void deleteRow() {
		//
    	if(NT_ID==null){
			return;
		}
        if(DbHelper.checkPhanQuyen(DbHelper.DELETE, "nhap_thuoc")==false){
            logger.info("YOU (" + DbHelper.getCurrentSessionUserName() + "), DON'T HAVE DELETE RIGHT for table nhap_thuoc");
            return;
        }
		Connection connection = null;

		try {
			connection = DbHelper.getSql2o();
            connection.setRollbackOnException(false);
			String sql = "delete from nhap_thuoc where NT_ID=:NT_ID";
			connection
					.createQuery(
							sql,
							true)
					.addParameter("NT_ID", this.NT_ID)
					.executeUpdate();
			logger.error("Delete Row [nhap_thuoc] OK: ID=["+NT_ID +"].");
            connection
					.createQuery(
							"insert into action_log(u_id,u_action,dbtable,actionid,fieldid) values(:u_id,:u_action,:dbtable,:actionid,:fieldid)",
							true)
					.addParameter("u_id", DbHelper.getCurrentSessionUserId())
					.addParameter("u_action", "Update nhap_thuoc. ID="+NT_ID)
                    .addParameter("dbtable", "nhap_thuoc")
                    .addParameter("fieldid", NT_ID)
					.addParameter("actionid", 4)
					.executeUpdate();
		} catch (Exception t) {
			logger.error("Delete [nhap_thuoc] Error: ID=["+NT_ID +"]."+"\nException=\n"+ t);
			throw new RuntimeException("Delete [nhap_thuoc]. ID=["+NT_ID + " ERROR: "+t.getMessage(), t);
		}
	}
    
    public String getIndex(int idx){
        switch(idx){
            case 0:
                // java.lang.Integer   
                if(this.V_ID!=null)
                    return this.V_ID.toString();
                else
                    return "N/A";
            case 1:
                // java.lang.Integer   
                if(this.KHO_ID!=null)
                    return this.KHO_ID.toString();
                else
                    return "N/A";
            case 2:
                // java.lang.String    
                if(this.VENDOR_NAME!=null)
                    return this.VENDOR_NAME.toString();
                else
                    return "N/A";
            case 3:
                // java.lang.Date      
                if(this.NGAY_NHAP!=null)
                    return this.NGAY_NHAP.toString();
                else
                    return "N/A";
            case 4:
                // java.lang.String    
                if(this.TENKHO!=null)
                    return this.TENKHO.toString();
                else
                    return "N/A";
            case 5:
                // java.lang.String    
                if(this.HOADON!=null)
                    return this.HOADON.toString();
                else
                    return "N/A";
            case 6:
                // java.lang.Integer   
                if(this.TONGCONG!=null)
                    return this.TONGCONG.toString();
                else
                    return "N/A";
            case 7:
                // java.lang.Integer   
                if(this.STS!=null)
                    return this.STS.toString();
                else
                    return "N/A";
            default:
        }
        return "";
    }
}